[tox]
envlist =
    flake8
    py{39,310,311}-dj42-cms311


skip_missing_interpreters=True


[testenv]
deps =
    -r{toxinidir}/tests/requirements.txt
    dj42: Django>=4.2,<5.0
    cms311: django-cms>=3.11,<3.12
commands =
    {envpython} --version
;    {env:COMMAND:coverage} erase
    {env:COMMAND:coverage} run setup.py test
;    {env:COMMAND:coverage} report

[flake8]
max-line-length = 120
exclude = */docs/*,*/migrations/*
