
# Generated by Django 1.11 on 2018-08-07 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_reversion2', '0004_auto_20170526_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageversion',
            options={'default_permissions': ()},
        ),
    ]
