
# Generated by Django 1.11 on 2018-08-30 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import versionfield


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_reversion2', '0006_pageversion_version_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageversion',
            name='comment',
            field=models.TextField(blank=True, help_text='Particular information concerning this Version', verbose_name='Version Comment'),
        ),
        migrations.AlterField(
            model_name='pageversion',
            name='title',
            field=models.CharField(blank=True, max_length=63, verbose_name='Version Title'),
        ),
        migrations.AlterField(
            model_name='pageversion',
            name='version_id',
            field=versionfield.VersionField(blank=True, null=True, verbose_name='Version Id'),
        ),
    ]
