from django.conf import settings

EXCLUDE_VERSIONS_FROM_SEARCH = getattr(settings, 'REVERSION2_EXCLUDE_VERSIONS_FROM_SEARCH', True)

# Include/Exclude templates
EXCLUDE_TEMPLATES = getattr(settings, 'REVERSION2_EXCLUDE_TEMPLATES', [])
INCLUDE_TEMPLATES = getattr(settings, 'REVERSION2_INCLUDE_TEMPLATES', [])

# Get Reversion Workflow Settings
# TODO MC?
ADD_VERSION_ON_PUBLISH = getattr(settings, 'REVERSION2_ADD_VERSION_ON_PUBLISH', True)
PROMPT_VERSION_ON_PUBLISH = getattr(settings, 'REVERSION2_PROMPT_VERSION_ON_PUBLISH', True)
ADD_VERSION_ON_REVERT = getattr(settings, 'REVERSION2_ADD_VERSION_ON_REVERT', False)
BATCH_ADD_UNVERSIONED_ONLY = getattr(settings, 'REVERSION2_BATCH_ADD_UNVERSIONED_ONLY', True)
PUBLISH_HIDDEN_PAGE = getattr(settings, 'REVERSION2_PUBLISH_HIDDEN_PAGE', True)

# Get User Interface Settings
ALLOW_MANUAL_SNAPSHOTS = getattr(settings, 'REVERSION2_ALLOW_MANUAL_SNAPSHOTS', True)
ALLOW_VERSION_EDIT = getattr(settings, 'REVERSION2_ALLOW_VERSION_EDIT', False)
ALLOW_BLANK_TITLE = getattr(settings, 'REVERSION2_ALLOW_BLANK_TITLE', False)

# Get Application Settings
REVERSION2_DIFF_TEXT_ONLY = getattr(settings, 'REVERSION2_DIFF_TEXT_ONLY', False)
REVERSION2_IGNORE_WHITESPACE = getattr(settings, 'REVERSION2_IGNORE_WHITESPACE', False)

# Get Version Settings
VERSION_ROOT_TITLE = getattr(settings, 'DJANGOCMS_REVERSION2_VERSION_ROOT_TITLE', '.~VERSIONS')
VERSION_START_VALUE = getattr(settings, 'DJANGOCMS_REVERSION2_VERSION_START_VALUE', '0.0.0')

# Get Bin Settings
BIN_ROOT_TITLE = getattr(settings, 'DJANGOCMS_REVERSION2_BIN_ROOT_TITLE', '.~DELETED')
BIN_PAGE_LANGUAGE = getattr(settings, 'LANGUAGE_CODE')
BIN_BUCKET_NAMING = getattr(settings, 'DJANGOCMS_REVERSION2_BIN_BUCKET_NAMING', '.DELETED_%Y-%m-%d')

